//! Account integration routes.
//!
//! Extracted to its own submodule (mirroring `api::syncplay`) to keep
//! `api::mod`'s ccn in check — adding the eight new handlers inline
//! would push that file's CRAP score over the ratchet ceiling.
//!
//! Routes mounted by [`router`]:
//!
//! | Method   | Path                                | Purpose |
//! |----------|-------------------------------------|---------|
//! | POST     | /api/account/auth-url/:provider     | Build OAuth authorize URL + return PKCE pair |
//! | POST     | /api/account/exchange-code/:provider | Exchange code for tokens (renderer persists via safeStorage) |
//! | POST     | /api/account/me/:provider           | Fetch profile (Authorization: Bearer header) |
//! | POST     | /api/account/list/:provider         | Fetch + cache list (Authorization: Bearer header) |
//! | GET      | /api/account/list/:provider/cached  | Read cached list (`?user_id=…`) |
//! | DELETE   | /api/account/list/:provider/cache   | Drop cache rows (`?user_id=…`) |
//!
//! Statelessness: the backend holds NO token state. Every authenticated
//! call carries the bearer in `Authorization: Bearer …`. The renderer
//! reads tokens from Electron's `safeStorage` on every call. See
//! `commands::account` doc for the full lifecycle.

use std::sync::Arc;

use axum::extract::{Path, State};
use axum::http::HeaderMap;
use axum::http::StatusCode;
use axum::routing::{delete, get, post};
use axum::{Json, Router};
use serde::{Deserialize, Serialize};

use crate::account::pkce::{Pkce, PkceMethod};
use crate::account::provider::{ListEntry, ProviderKind, Tokens, UserProfile};
use crate::app::AppState;
use crate::commands::account;
use crate::error::AniError;

/// Mount the account routes onto the given app state. Called from
/// [`crate::api::build_api_router`].
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/api/account/auth-url/:provider", post(post_auth_url))
        .route(
            "/api/account/exchange-code/:provider",
            post(post_exchange_code),
        )
        .route("/api/account/me/:provider", post(post_me))
        .route("/api/account/list/:provider", post(post_list))
        .route("/api/account/list/:provider/cached", get(get_cached_list))
        .route(
            "/api/account/list/:provider/cache",
            delete(delete_list_cache),
        )
}

// — Wire types — — — — — — — — — — — — — — — — — — — — — — — — — — —

/// Renderer-supplied PKCE pair. Renderer keeps the verifier locally
/// between auth-url and exchange-code so the backend stays stateless.
#[derive(Debug, Deserialize)]
pub struct PkceWire {
    /// 43..=128 chars per RFC 7636.
    pub verifier: String,
    /// Computed by the renderer using the method appropriate for the
    /// provider (plain for MAL, S256 for AniList — though AniList
    /// ignores PKCE entirely).
    pub challenge: String,
    /// "plain" or "S256".
    pub method: String,
}

impl PkceWire {
    fn into_pkce(self) -> Option<Pkce> {
        let method = match self.method.as_str() {
            "plain" => PkceMethod::Plain,
            "S256" => PkceMethod::S256,
            _ => return None,
        };
        Some(Pkce {
            verifier: self.verifier,
            challenge: self.challenge,
            method,
        })
    }
}

#[derive(Debug, Deserialize)]
pub struct AuthUrlRequest {
    /// CSRF token the renderer generated. The OAuth callback page
    /// echoes it back; renderer verifies before exchange-code.
    pub state: String,
    /// PKCE pair generated by the renderer (or, easier, asked from
    /// the backend via [`account::pkce_for_kind`] over a separate
    /// route — but we accept the renderer's pair here for symmetry).
    pub pkce: PkceWire,
}

#[derive(Debug, Serialize)]
pub struct AuthUrlResponse {
    pub url: String,
}

#[derive(Debug, Deserialize)]
pub struct ExchangeCodeRequest {
    /// Authorization code from the OAuth callback.
    pub code: String,
    /// Verifier the renderer kept locally between auth-url and exchange.
    pub pkce: PkceWire,
}

#[derive(Debug, Serialize)]
pub struct TokensResponse {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at_epoch_s: i64,
}

impl From<Tokens> for TokensResponse {
    fn from(t: Tokens) -> Self {
        Self {
            access_token: t.access_token,
            refresh_token: t.refresh_token,
            expires_at_epoch_s: t.expires_at_epoch_s,
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct ListRequest {
    /// User id the renderer learned from a prior `me` call. The backend
    /// can't derive this from the bearer cheaply — every provider
    /// implements a separate user-info endpoint — so the renderer
    /// passes it along to scope the cache write.
    pub user_id: String,
}

// — Handlers — — — — — — — — — — — — — — — — — — — — — — — — — — — — —

fn parse_provider(slug: &str) -> Result<ProviderKind, AniError> {
    ProviderKind::from_slug(slug).ok_or(AniError::Metadata)
}

fn bearer_from_headers(headers: &HeaderMap) -> Result<String, AniError> {
    let auth = headers
        .get(axum::http::header::AUTHORIZATION)
        .ok_or(AniError::InvalidToken)?;
    let raw = auth.to_str().map_err(|_| AniError::InvalidToken)?;
    let token = raw
        .strip_prefix("Bearer ")
        .ok_or(AniError::InvalidToken)?
        .trim();
    if token.is_empty() {
        return Err(AniError::InvalidToken);
    }
    Ok(token.to_owned())
}

async fn post_auth_url(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    Json(req): Json<AuthUrlRequest>,
) -> Result<Json<AuthUrlResponse>, AniError> {
    let kind = parse_provider(&provider)?;
    let pkce = req.pkce.into_pkce().ok_or(AniError::Metadata)?;
    let url = account::auth_url(&state, kind, &req.state, &pkce)?;
    Ok(Json(AuthUrlResponse { url }))
}

async fn post_exchange_code(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    Json(req): Json<ExchangeCodeRequest>,
) -> Result<Json<TokensResponse>, AniError> {
    let kind = parse_provider(&provider)?;
    let pkce = req.pkce.into_pkce().ok_or(AniError::Metadata)?;
    let tokens = account::exchange_code(&state, kind, &req.code, &pkce).await?;
    Ok(Json(tokens.into()))
}

async fn post_me(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    headers: HeaderMap,
) -> Result<Json<UserProfile>, AniError> {
    let kind = parse_provider(&provider)?;
    let bearer = bearer_from_headers(&headers)?;
    let tokens = account::tokens_from_bearer(&bearer);
    let profile = account::me(&state, kind, &tokens).await?;
    Ok(Json(profile))
}

async fn post_list(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    headers: HeaderMap,
    Json(req): Json<ListRequest>,
) -> Result<Json<Vec<ListEntry>>, AniError> {
    let kind = parse_provider(&provider)?;
    let bearer = bearer_from_headers(&headers)?;
    let tokens = account::tokens_from_bearer(&bearer);
    let entries = account::list_all_and_cache(&state, kind, &tokens, &req.user_id).await?;
    Ok(Json(entries))
}

async fn get_cached_list(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    headers: HeaderMap,
) -> Result<Json<Vec<ListEntry>>, AniError> {
    // Codex P1 #3369956138: the prior fix only validated the bearer
    // syntactically (presence of `Bearer <something>`), then trusted
    // `?user_id=` from the query. Under the permissive CORS layer any
    // browser tab could send `Authorization: Bearer anything` plus a
    // guessed AniList id and read another user's cached rows.
    //
    // Real fix: derive the user_id from the bearer by calling the
    // provider's `me` endpoint. If the bearer is forged the upstream
    // call fails with 401 and we surface InvalidToken; if it's
    // genuine we look up cache for the verified id, not whatever the
    // caller claimed in the query.
    let bearer = bearer_from_headers(&headers)?;
    let kind = parse_provider(&provider)?;
    let tokens = account::tokens_from_bearer(&bearer);
    let profile = account::me(&state, kind, &tokens).await?;
    let entries = account::cached_list(&state, kind, &profile.user_id)?;
    Ok(Json(entries))
}

async fn delete_list_cache(
    State(state): State<Arc<AppState>>,
    Path(provider): Path<String>,
    headers: HeaderMap,
) -> Result<StatusCode, AniError> {
    // Same upstream-validated identity as get_cached_list — a forged
    // bearer can't be used to wipe another user's cache rows.
    let bearer = bearer_from_headers(&headers)?;
    let kind = parse_provider(&provider)?;
    let tokens = account::tokens_from_bearer(&bearer);
    let profile = account::me(&state, kind, &tokens).await?;
    account::clear_cache(&state, kind, &profile.user_id)?;
    Ok(StatusCode::NO_CONTENT)
}

#[cfg(test)]
#[path = "account_test.rs"]
mod tests;
