//! Wire types for the `/api/account/*` routes — the renderer-facing
//! request/response structs and their conversions. Split out of
//! `api/account.rs` so the handler module's CRAP stays under the
//! ratchet ceiling: these are pure data + serde with no I/O, and the
//! handler file was already at the cap before the token-refresh route
//! landed.

use serde::{Deserialize, Serialize};

use crate::account::pkce::{Pkce, PkceMethod};
use crate::account::provider::Tokens;

/// Renderer-supplied PKCE pair. Renderer keeps the verifier locally
/// between auth-url and exchange-code so the backend stays stateless.
#[derive(Debug, Deserialize)]
pub struct PkceWire {
    /// 43..=128 chars per RFC 7636.
    pub verifier: String,
    /// Computed by the renderer using the method appropriate for the
    /// provider (plain for MAL, S256 for AniList — though AniList
    /// ignores PKCE entirely).
    pub challenge: String,
    /// "plain" or "S256".
    pub method: String,
}

impl PkceWire {
    pub(super) fn into_pkce(self) -> Option<Pkce> {
        let method = match self.method.as_str() {
            "plain" => PkceMethod::Plain,
            "S256" => PkceMethod::S256,
            _ => return None,
        };
        Some(Pkce {
            verifier: self.verifier,
            challenge: self.challenge,
            method,
        })
    }
}

#[derive(Debug, Deserialize)]
pub struct AuthUrlRequest {
    /// CSRF token the renderer generated. The OAuth callback page
    /// echoes it back; renderer verifies before exchange-code.
    pub state: String,
    /// PKCE pair generated by the renderer (or, easier, asked from
    /// the backend via [`crate::commands::account::pkce_for_kind`] over
    /// a separate route — but we accept the renderer's pair here for
    /// symmetry).
    pub pkce: PkceWire,
}

#[derive(Debug, Serialize)]
pub struct AuthUrlResponse {
    pub url: String,
}

#[derive(Debug, Deserialize)]
pub struct ExchangeCodeRequest {
    /// Authorization code from the OAuth callback.
    pub code: String,
    /// Verifier the renderer kept locally between auth-url and exchange.
    pub pkce: PkceWire,
}

#[derive(Debug, Deserialize)]
pub struct RefreshRequest {
    /// The persisted refresh token. The renderer holds it (the backend
    /// is stateless) and posts it here when an access token has expired
    /// but is still refreshable — MAL's ~1h access token against its
    /// long-lived refresh token.
    pub refresh_token: String,
}

#[derive(Debug, Serialize)]
pub struct TokensResponse {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at_epoch_s: i64,
}

impl From<Tokens> for TokensResponse {
    fn from(t: Tokens) -> Self {
        Self {
            access_token: t.access_token,
            refresh_token: t.refresh_token,
            expires_at_epoch_s: t.expires_at_epoch_s,
        }
    }
}

/// Renderer-supplied write-back payload for `POST /update/:provider`.
/// The renderer fires this once per connected provider on mark-watched,
/// each with that provider's bearer in the `Authorization` header. The
/// backend resolves the provider-native media id from `kitsu_id` (the
/// only id the play context carries). All update fields are optional —
/// omitted means "leave unchanged"; `status` is the unified snake_case
/// form (`watching`, `completed`, …).
#[derive(Debug, Deserialize)]
pub struct UpdateProgressRequest {
    /// Kitsu id of the show being marked watched.
    pub kitsu_id: String,
    /// New episodes-watched count.
    #[serde(default)]
    pub progress: Option<u32>,
    /// New unified status (snake_case). `None` leaves it unchanged.
    #[serde(default)]
    pub status: Option<String>,
    /// New score on the unified 0..=100 scale.
    #[serde(default)]
    pub score: Option<u8>,
}

/// Renderer-supplied fallback identity for the cache DELETE path
/// (Codex P2 #3369997650). Consulted ONLY when the bearer's `me()` call
/// fails with `InvalidToken` — disconnect-after-expiry needs to clear
/// the cache but the bearer is no longer trusted upstream. Trusting
/// this in the live-bearer path would re-enable the cross-origin
/// poisoning Codex P1 #3369956138 closed.
#[derive(Debug, Deserialize)]
pub struct DisconnectFallbackQuery {
    /// The user_id the renderer learned from a prior successful
    /// `me()` (persisted in safeStorage). Used only as a fallback.
    #[serde(default)]
    pub fallback_user_id: Option<String>,
}

/// Renderer-supplied payload for the explicit detail-page list editor
/// (`POST /set/:provider`). Unlike [`UpdateProgressRequest`] (the
/// automatic mark-watched fan-out) this is a deliberate user edit, so
/// the backend writes it verbatim — no monotonic guard. At least one of
/// `status` / `progress` must be present (enforced by `build_entry_update`).
#[derive(Debug, Deserialize)]
pub struct SetEntryRequest {
    /// Kitsu id of the show being edited.
    pub kitsu_id: String,
    /// New unified status (snake_case), or `None` to leave unchanged.
    #[serde(default)]
    pub status: Option<String>,
    /// New episodes-watched count, or `None` to leave unchanged.
    #[serde(default)]
    pub progress: Option<u32>,
}

/// Query string carrying the Kitsu id for the entry read/delete routes
/// (`GET`/`DELETE /entry/:provider?kitsu_id=…`).
#[derive(Debug, Deserialize)]
pub struct EntryQuery {
    /// Kitsu id of the show whose entry is read or removed.
    pub kitsu_id: String,
}

/// The live current list entry for one show, returned by
/// `GET /entry/:provider`. `null` (the route returns `Option`) means the
/// show isn't on the user's list or isn't mapped to the provider.
#[derive(Debug, Serialize)]
pub struct EntryView {
    /// Unified status (snake_case) — matches `SetEntryRequest::status`.
    pub status: String,
    /// Episodes watched so far.
    pub progress: u32,
}

#[cfg(test)]
#[path = "account_wire_test.rs"]
mod tests;
