//! Account integration handlers — the per-route bodies the
//! [`crate::api::account`] submodule mounts.
//!
//! Statelessness contract: the backend holds NO session state. Every
//! handler that talks to a provider receives the bearer in the request
//! header (extracted before reaching these functions). Tokens live in
//! Electron's `safeStorage` on disk + renderer memory; the Rust process
//! is a pure proxy + cache.
//!
//! Why: the Rust binary is also the test target (`cargo test`) and
//! can't depend on an Electron runtime to read the keychain. Pushing
//! token persistence to Electron keeps the backend deterministic and
//! testable.
//!
//! Token lifecycle (see `.planning/account-integration.md` §3.4):
//!
//! 1. Renderer → backend `auth_url` → returns URL + state + pkce
//! 2. Renderer → Electron main: open browser, listen on :53682
//! 3. Browser redirects to localhost callback with `?code=&state=`
//! 4. Renderer → backend `exchange_code` → returns Tokens
//! 5. Renderer → Electron main: safeStorage-encrypt + persist
//! 6. Renderer → backend `me` / `list_all` with `Authorization: Bearer`

use std::sync::Arc;

use crate::account::pkce::Pkce;
use crate::account::provider::{ListEntry, ProviderKind, Tokens, UserListProvider, UserProfile};
use crate::account::status::ListStatus;
use crate::app::AppState;
use crate::cache::SqlitePool;
use crate::error::{AniError, Result};
use crate::meta::anilist_user::AniListProvider;

/// Build a [`UserListProvider`] for the requested provider kind. Used
/// by every route handler that calls into a concrete provider.
///
/// PR #3 (MAL adapter) will add the `MyAnimeList` branch; PR #4+
/// (in-house) eventually adds the third. Today MAL and InHouse return
/// [`AniError::Metadata`] — the routes that dispatch by slug guard
/// against unsupported kinds at the slug-parse step, but defending
/// here too keeps the dispatcher honest.
#[must_use]
pub fn provider_for_kind(
    kind: ProviderKind,
    client: reqwest::Client,
) -> Option<Box<dyn UserListProvider>> {
    match kind {
        ProviderKind::AniList => Some(Box::new(AniListProvider::new(client))),
        ProviderKind::MyAnimeList | ProviderKind::InHouse => None,
    }
}

/// Build the authorize-URL the renderer hands to Electron's
/// `shell.openExternal`. The renderer must persist `state` + the PKCE
/// pair so the exchange-code handler can verify them later (CSRF).
///
/// `state` is generated by the renderer (CSRF token). `pkce` is
/// generated by the renderer per the provider's method requirement
/// (plain for MAL, S256 for the future in-house, ignored by AniList
/// but generated for trait symmetry).
pub fn auth_url(
    state: &Arc<AppState>,
    kind: ProviderKind,
    csrf: &str,
    pkce: &Pkce,
) -> Result<String> {
    let Some(provider) = provider_for_kind(kind, state.proxy_http.clone()) else {
        return Err(AniError::Metadata);
    };
    Ok(provider.auth_url(pkce, csrf))
}

/// Exchange an OAuth authorization code for tokens. Renderer then
/// passes the returned [`Tokens`] to Electron main for `safeStorage`
/// encryption.
pub async fn exchange_code(
    state: &Arc<AppState>,
    kind: ProviderKind,
    code: &str,
    pkce: &Pkce,
) -> Result<Tokens> {
    let Some(provider) = provider_for_kind(kind, state.proxy_http.clone()) else {
        return Err(AniError::Metadata);
    };
    provider.exchange_code(code, pkce).await
}

/// Fetch the authenticated user's profile. Routes use this to populate
/// the AccountChip avatar + `/account` page stats.
pub async fn me(state: &Arc<AppState>, kind: ProviderKind, tokens: &Tokens) -> Result<UserProfile> {
    let Some(provider) = provider_for_kind(kind, state.proxy_http.clone()) else {
        return Err(AniError::Metadata);
    };
    provider.me(tokens).await
}

/// Fetch the full user list (all statuses) and write it through the
/// cache. Returns the freshly-fetched entries (not the cache contents
/// — caller can fan them out to surfaces without an extra read).
pub async fn list_all_and_cache(
    state: &Arc<AppState>,
    kind: ProviderKind,
    tokens: &Tokens,
    user_id: &str,
) -> Result<Vec<ListEntry>> {
    let Some(provider) = provider_for_kind(kind, state.proxy_http.clone()) else {
        return Err(AniError::Metadata);
    };
    let entries = provider.list_all(tokens).await?;
    write_through_cache(&state.cache_pool, kind, user_id, &entries)?;
    Ok(entries)
}

/// Read the cached list. Used by PR #2's home Watch Later rail to
/// avoid an upstream round-trip on every paint.
pub fn cached_list(
    state: &Arc<AppState>,
    kind: ProviderKind,
    user_id: &str,
) -> Result<Vec<ListEntry>> {
    crate::account::cache::list_entries(&state.cache_pool, kind, user_id)
}

/// Drop every cached row for `(kind, user_id)` — called on disconnect.
pub fn clear_cache(state: &Arc<AppState>, kind: ProviderKind, user_id: &str) -> Result<()> {
    crate::account::cache::clear_user(&state.cache_pool, kind, user_id)
}

fn write_through_cache(
    pool: &SqlitePool,
    kind: ProviderKind,
    user_id: &str,
    entries: &[ListEntry],
) -> Result<()> {
    crate::account::cache::write_entries(pool, kind, user_id, entries)
}

/// Decode the `Authorization: Bearer <token>` header value into a
/// [`Tokens`] envelope. `expires_at_epoch_s` is zero because the
/// header doesn't carry expiry — that's tracked in the renderer's
/// token store and acted on (refresh / reauth) before the handler is
/// called. PR #4 adds a richer header that round-trips the expiry.
#[must_use]
pub fn tokens_from_bearer(bearer: &str) -> Tokens {
    Tokens {
        access_token: bearer.to_owned(),
        refresh_token: None,
        expires_at_epoch_s: 0,
    }
}

/// Build a fresh PKCE pair appropriate for the provider's method
/// requirement. AniList ignores PKCE but we still pick S256 for trait
/// symmetry; MAL requires `plain`.
#[must_use]
pub fn pkce_for_kind(kind: ProviderKind) -> Pkce {
    match kind {
        ProviderKind::MyAnimeList => Pkce::new_plain(),
        ProviderKind::AniList | ProviderKind::InHouse => Pkce::new_s256(),
    }
}

/// Translate the unified [`ListStatus`] into the snake_case string the
/// SQL cache stores. Mirrors `#[serde(rename_all = "snake_case")]`
/// without round-tripping through JSON.
#[must_use]
pub fn status_to_snake(s: ListStatus) -> &'static str {
    match s {
        ListStatus::Planning => "planning",
        ListStatus::Watching => "watching",
        ListStatus::Completed => "completed",
        ListStatus::Paused => "paused",
        ListStatus::Dropped => "dropped",
        ListStatus::Rewatching => "rewatching",
    }
}

/// Inverse of [`status_to_snake`]. Used by [`crate::account::cache`]
/// when reading rows back into typed [`ListEntry`].
#[must_use]
pub fn status_from_snake(s: &str) -> Option<ListStatus> {
    match s {
        "planning" => Some(ListStatus::Planning),
        "watching" => Some(ListStatus::Watching),
        "completed" => Some(ListStatus::Completed),
        "paused" => Some(ListStatus::Paused),
        "dropped" => Some(ListStatus::Dropped),
        "rewatching" => Some(ListStatus::Rewatching),
        _ => None,
    }
}

#[cfg(test)]
#[path = "account_test.rs"]
mod tests;
