//! Account integration handlers — the per-route bodies the
//! [`crate::api::account`] submodule mounts.
//!
//! Statelessness contract: the backend holds NO session state. Every
//! handler that talks to a provider receives the bearer in the request
//! header (extracted before reaching these functions). Tokens live in
//! Electron's `safeStorage` on disk + renderer memory; the Rust process
//! is a pure proxy + cache.
//!
//! Why: the Rust binary is also the test target (`cargo test`) and
//! can't depend on an Electron runtime to read the keychain. Pushing
//! token persistence to Electron keeps the backend deterministic and
//! testable.
//!
//! Token lifecycle (see `.planning/account-integration.md` §3.4):
//!
//! 1. Renderer → backend `auth_url` → returns URL + state + pkce
//! 2. Renderer → Electron main: open browser, listen on :53682
//! 3. Browser redirects to localhost callback with `?code=&state=`
//! 4. Renderer → backend `exchange_code` → returns Tokens
//! 5. Renderer → Electron main: safeStorage-encrypt + persist
//! 6. Renderer → backend `me` / `list_all` with `Authorization: Bearer`

use std::sync::Arc;

use crate::account::pkce::Pkce;
use crate::account::provider::{
    EntryUpdate, ListEntry, ProviderKind, ProviderMediaId, Tokens, UserListProvider, UserProfile,
};
use crate::account::status::ListStatus;
use crate::app::AppState;
use crate::cache::SqlitePool;
use crate::error::{AniError, Result};
use crate::meta::anilist_user::AniListProvider;
use crate::meta::mal_user::MalProvider;

/// Build a [`UserListProvider`] for the requested provider kind. Used
/// by every route handler that calls into a concrete provider. Takes
/// the whole [`AppState`] so MAL can pull the process-wide refresh
/// coalesce cache off it — without that shared cache, two concurrent
/// handlers each build their own `MalProvider` with its own mutex and
/// both POST the same stale refresh token (Codex P2 #3379969316).
///
/// PR #4+ (in-house) eventually adds the third branch. Today InHouse
/// returns `None` — the routes that dispatch by slug guard against
/// unsupported kinds at the slug-parse step, but defending here too
/// keeps the dispatcher honest.
#[must_use]
pub fn provider_for_kind(
    state: &Arc<AppState>,
    kind: ProviderKind,
) -> Option<Box<dyn UserListProvider>> {
    let client = state.proxy_http.clone();
    match kind {
        ProviderKind::AniList => Some(Box::new(AniListProvider::new(client))),
        ProviderKind::MyAnimeList => Some(Box::new(MalProvider::new(
            client,
            state.mal_refresh.clone(),
        ))),
        ProviderKind::InHouse => None,
    }
}

/// Build the authorize-URL the renderer hands to Electron's
/// `shell.openExternal`. The renderer must persist `state` + the PKCE
/// pair so the exchange-code handler can verify them later (CSRF).
///
/// `state` is generated by the renderer (CSRF token). `pkce` is
/// generated by the renderer per the provider's method requirement
/// (plain for MAL, S256 for the future in-house, ignored by AniList
/// but generated for trait symmetry).
pub fn auth_url(
    state: &Arc<AppState>,
    kind: ProviderKind,
    csrf: &str,
    pkce: &Pkce,
) -> Result<String> {
    let Some(provider) = provider_for_kind(state, kind) else {
        return Err(AniError::Metadata);
    };
    provider.auth_url(pkce, csrf)
}

/// Exchange an OAuth authorization code for tokens. Renderer then
/// passes the returned [`Tokens`] to Electron main for `safeStorage`
/// encryption.
pub async fn exchange_code(
    state: &Arc<AppState>,
    kind: ProviderKind,
    code: &str,
    pkce: &Pkce,
) -> Result<Tokens> {
    let Some(provider) = provider_for_kind(state, kind) else {
        return Err(AniError::Metadata);
    };
    provider.exchange_code(code, pkce).await
}

/// Fetch the authenticated user's profile. Routes use this to populate
/// the AccountChip avatar + `/account` page stats.
pub async fn me(state: &Arc<AppState>, kind: ProviderKind, tokens: &Tokens) -> Result<UserProfile> {
    let Some(provider) = provider_for_kind(state, kind) else {
        return Err(AniError::Metadata);
    };
    provider.me(tokens).await
}

/// Fetch the full user list (all statuses) and write it through the
/// cache. Returns the freshly-fetched entries (not the cache contents
/// — caller can fan them out to surfaces without an extra read).
pub async fn list_all_and_cache(
    state: &Arc<AppState>,
    kind: ProviderKind,
    tokens: &Tokens,
    user_id: &str,
) -> Result<Vec<ListEntry>> {
    let Some(provider) = provider_for_kind(state, kind) else {
        return Err(AniError::Metadata);
    };
    let entries = provider.list_all(tokens).await?;
    write_through_cache(&state.cache_pool, kind, user_id, &entries)?;
    Ok(entries)
}

/// Read the cached list. Used by PR #2's home Watch Later rail to
/// avoid an upstream round-trip on every paint.
pub fn cached_list(
    state: &Arc<AppState>,
    kind: ProviderKind,
    user_id: &str,
) -> Result<Vec<ListEntry>> {
    crate::account::cache::list_entries(&state.cache_pool, kind, user_id)
}

/// Drop every cached row for `(kind, user_id)` — called on disconnect.
pub fn clear_cache(state: &Arc<AppState>, kind: ProviderKind, user_id: &str) -> Result<()> {
    crate::account::cache::clear_user(&state.cache_pool, kind, user_id)
}

/// Drop every cached row for `kind` regardless of `user_id`. Codex P2
/// #3371658227: the renderer's safeStorage-orphan-disconnect path has
/// no `user_id` to pass — the token file existed but the keychain
/// couldn't decrypt it on hydrate — so we can't run the per-user
/// clear. The API boundary still gates this on the renderer-only
/// internal secret so a cross-origin tab can't wipe a stranger's
/// cache by guessing nothing.
pub fn clear_provider_cache(state: &Arc<AppState>, kind: ProviderKind) -> Result<()> {
    crate::account::cache::clear_provider(&state.cache_pool, kind)
}

fn write_through_cache(
    pool: &SqlitePool,
    kind: ProviderKind,
    user_id: &str,
    entries: &[ListEntry],
) -> Result<()> {
    crate::account::cache::write_entries(pool, kind, user_id, entries)
}

/// Decode the `Authorization: Bearer <token>` header value into a
/// [`Tokens`] envelope. `expires_at_epoch_s` is zero because the
/// header doesn't carry expiry — that's tracked in the renderer's
/// token store and acted on (refresh / reauth) before the handler is
/// called. PR #4 adds a richer header that round-trips the expiry.
#[must_use]
pub fn tokens_from_bearer(bearer: &str) -> Tokens {
    Tokens {
        access_token: bearer.to_owned(),
        refresh_token: None,
        expires_at_epoch_s: 0,
    }
}

/// Build a fresh PKCE pair appropriate for the provider's method
/// requirement. AniList ignores PKCE but we still pick S256 for trait
/// symmetry; MAL requires `plain`.
#[must_use]
pub fn pkce_for_kind(kind: ProviderKind) -> Pkce {
    match kind {
        ProviderKind::MyAnimeList => Pkce::new_plain(),
        ProviderKind::AniList | ProviderKind::InHouse => Pkce::new_s256(),
    }
}

/// Translate the unified [`ListStatus`] into the snake_case string the
/// SQL cache stores. Mirrors `#[serde(rename_all = "snake_case")]`
/// without round-tripping through JSON.
#[must_use]
pub fn status_to_snake(s: ListStatus) -> &'static str {
    match s {
        ListStatus::Planning => "planning",
        ListStatus::Watching => "watching",
        ListStatus::Completed => "completed",
        ListStatus::Paused => "paused",
        ListStatus::Dropped => "dropped",
        ListStatus::Rewatching => "rewatching",
    }
}

/// Inverse of [`status_to_snake`]. Used by [`crate::account::cache`]
/// when reading rows back into typed [`ListEntry`].
#[must_use]
pub fn status_from_snake(s: &str) -> Option<ListStatus> {
    match s {
        "planning" => Some(ListStatus::Planning),
        "watching" => Some(ListStatus::Watching),
        "completed" => Some(ListStatus::Completed),
        "paused" => Some(ListStatus::Paused),
        "dropped" => Some(ListStatus::Dropped),
        "rewatching" => Some(ListStatus::Rewatching),
        _ => None,
    }
}

/// Cap on the renderer-supplied Watch-Later bridge batch. The home
/// rail's largest plausible Plan-to-Watch is a few hundred titles;
/// 500 leaves comfortable headroom while bounding the fan-out cost
/// per request to a fixed worst case. Codex P1 #3373789621: under
/// the permissive CORS layer a cross-origin page could otherwise
/// POST an unbounded `mal_ids` array and burn N concurrent Kitsu
/// requests per call.
pub const WATCH_LATER_BRIDGE_MAX_IDS: usize = 500;

/// Concurrent in-flight Kitsu `/mappings` lookups during the
/// Watch-Later bridge. Codex P2 #3373969321: `lookup_by_mal_id` is
/// uncached so a single rail load could fire up to
/// [`WATCH_LATER_BRIDGE_MAX_IDS`] requests in parallel and trip
/// Kitsu's upstream rate limit (the AniList trending bridge tops
/// out at 25 — well below the throttle threshold — and never hit
/// this; the rail's larger batch exposes it). 8 is well under the
/// observed safe parallelism for `/mappings` and keeps the
/// worst-case rail wall-clock under ~5s while still much faster
/// than serial.
const WATCH_LATER_BRIDGE_CONCURRENCY: usize = 8;

/// Bridge a list of MAL ids to Kitsu refs, preserving input order
/// and dropping ids Kitsu can't map. Used by the home page's Watch
/// Later rail (plan §6.6) so cached `user_list_cache` rows render
/// with the same Kitsu metadata + availability filter as the rest
/// of the home.
///
/// Concurrency is capped at [`WATCH_LATER_BRIDGE_CONCURRENCY`] via
/// `buffered(N)` so we don't queue up to 500 outbound Kitsu
/// requests at once (Codex P2 #3373969321).
///
/// Truncates `mal_ids` at [`WATCH_LATER_BRIDGE_MAX_IDS`] before
/// fan-out — the upstream gate (route handler) rejects oversize
/// batches outright, this cap is belt-and-suspenders so a missing
/// route-level check can't be exploited.
///
/// # Errors
/// Never fails the whole batch — individual lookup failures drop the
/// entry from the output. Empty input → empty output.
pub async fn kitsu_for_mal_ids(
    state: &Arc<AppState>,
    mal_ids: Vec<u32>,
) -> Vec<crate::meta::kitsu::KitsuAnimeRef> {
    use futures_util::stream::{self, StreamExt};

    let bounded = mal_ids
        .into_iter()
        .take(WATCH_LATER_BRIDGE_MAX_IDS)
        .collect::<Vec<_>>();
    stream::iter(bounded)
        .map(|mal_id| {
            let kitsu = state.kitsu.clone();
            async move { kitsu.lookup_by_mal_id(mal_id).await.ok().flatten() }
        })
        .buffered(WATCH_LATER_BRIDGE_CONCURRENCY)
        .filter_map(|maybe_ref| async move { maybe_ref })
        .collect()
        .await
}

/// Resolve a show's Kitsu id into the provider-native media id needed
/// by `update_entry`: MAL's anime id (the Kitsu→MAL mapping) for
/// MyAnimeList, and AniList's numeric `mediaId` (MAL id → AniList
/// `Media(idMal:)`) for AniList. `Ok(None)` when the show can't be
/// mapped (no MAL mapping, or AniList doesn't index it) — a non-error
/// "nothing to push" so the mark-watched fan-out skips it rather than
/// reporting a failure. `anilist_base` overrides the AniList endpoint
/// in tests; production passes `None`.
///
/// This is the live id-lookup foundation for write-back: both
/// providers' `update_entry` upsert, so resolving the native id is
/// all that's needed to push progress to a show — including one not
/// yet on the user's list (the basis for currently-watching tracking).
// Stub-`push_progress` (red commit) doesn't call this yet; the green
// commit's real body does, dropping this allow.
#[allow(dead_code)]
pub(crate) async fn resolve_native_media_id(
    state: &Arc<AppState>,
    kind: ProviderKind,
    kitsu_id: &str,
    anilist_base: Option<&str>,
) -> Result<Option<ProviderMediaId>> {
    // Every provider's native id keys off the show's MAL id, which
    // Kitsu's mappings carry. No MAL mapping → can't push anywhere.
    let Some(mal_id) = state.kitsu.mal_id_for_kitsu_id(kitsu_id).await? else {
        return Ok(None);
    };
    match kind {
        // MAL's anime id IS the mapped MAL id.
        ProviderKind::MyAnimeList => Ok(Some(ProviderMediaId(mal_id))),
        // AniList keys on its own numeric mediaId; bridge MAL → AniList.
        ProviderKind::AniList => {
            let media_id =
                crate::meta::anilist::media_id_for_mal(&state.proxy_http, mal_id, anilist_base)
                    .await?;
            Ok(media_id.map(ProviderMediaId))
        }
        // In-house provider has no external id space yet.
        ProviderKind::InHouse => Ok(None),
    }
}

/// Push `update` (progress / status / score) to a connected tracker
/// for the show identified by its Kitsu id. Called once per connected
/// provider by the mark-watched fan-out, each with that provider's
/// bearer.
///
/// Returns `Ok(None)` when the show can't be mapped to the provider
/// (no MAL mapping, or AniList doesn't index it) — a non-error "nothing
/// to push" so the fan-out treats it as a skip, not a failure.
/// `Ok(Some(entry))` carries the upserted entry (both providers'
/// `update_entry` create the list row if absent — the basis for
/// currently-watching tracking).
pub async fn push_progress(
    state: &Arc<AppState>,
    kind: ProviderKind,
    tokens: &Tokens,
    kitsu_id: &str,
    update: EntryUpdate,
) -> Result<Option<ListEntry>> {
    push_progress_with_anilist_base(state, kind, tokens, kitsu_id, update, None).await
}

/// Inner `push_progress` with the AniList endpoint override threaded
/// through to `resolve_native_media_id`. Production calls
/// `push_progress` (base `None`); tests pass a wiremock URI.
#[allow(unused_variables)]
async fn push_progress_with_anilist_base(
    state: &Arc<AppState>,
    kind: ProviderKind,
    tokens: &Tokens,
    kitsu_id: &str,
    update: EntryUpdate,
    anilist_base: Option<&str>,
) -> Result<Option<ListEntry>> {
    // Stub — green commit implements resolve + update_entry.
    Err(AniError::Metadata)
}

#[cfg(test)]
#[path = "account_test.rs"]
mod tests;
