#!/usr/bin/env python3
"""Print the canonical snapshot of a workflow directory.

One definition of the projection, used by both sides of the pin: the
architectural check compares this script's output against the recorded
snapshot, and the snapshot is regenerated by redirecting this script's
output into it.  Two implementations could disagree; one cannot.

    python3 tools/workflow-snapshot.py .github/workflows \\
        > tests/arch/workflows.snapshot.json

What is recorded, and why only this:

  * every workflow's resolved job names, so a second job answering for
    a required check name is a difference whatever syntax produced it
    — quoted, folded, aliased, merge-keyed, flow-styled;
  * the arch lint workflow's whole resolved structure, so a skipped
    step, a tolerated failure, a narrowed trigger or a swapped action
    is a difference too.

A step added to an unrelated workflow is not a difference, which keeps
the pin off everyday work.  Anything else about the workflows is
deliberately unpinned: this is a change detector, not a specification.
"""

import json
import os
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - reported by the caller
    yaml = None


def canon(node):
    """Stringify mapping keys so the result sorts and serialises.

    YAML 1.1 resolves a bare ``on:`` key to boolean ``True``, which
    cannot be ordered against the string keys beside it.
    """
    if isinstance(node, dict):
        return {str(key): canon(value) for key, value in node.items()}
    if isinstance(node, list):
        return [canon(value) for value in node]
    return node


def documents(path):
    with open(path, encoding="utf-8") as handle:
        return [canon(doc) for doc in yaml.safe_load_all(handle) if isinstance(doc, dict)]


def job_names(docs):
    """Resolved name per job id, falling back to the id when unnamed."""
    names = {}
    for doc in docs:
        jobs = doc.get("jobs")
        if not isinstance(jobs, dict):
            continue
        for jid, job in jobs.items():
            name = job.get("name") if isinstance(job, dict) else None
            names[str(jid)] = name if isinstance(name, str) else str(jid)
    return names


def snapshot(workflow_dir):
    names = {}
    for entry in sorted(os.listdir(workflow_dir)):
        if entry.endswith((".yml", ".yaml")):
            names[entry] = job_names(documents(os.path.join(workflow_dir, entry)))
    arch_lint = os.path.join(workflow_dir, "arch-lint.yml")
    return {
        "check_names": names,
        "arch_lint": documents(arch_lint) if os.path.exists(arch_lint) else [],
    }


if __name__ == "__main__":
    if yaml is None:
        print("workflow-snapshot: PyYAML is not importable", file=sys.stderr)
        raise SystemExit(1)
    if len(sys.argv) != 2:
        print("usage: workflow-snapshot.py <workflow-dir>", file=sys.stderr)
        raise SystemExit(2)
    print(json.dumps(snapshot(sys.argv[1]), sort_keys=True, indent=2))
