# Added due to required but conditional checks
# Read more: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: 'bash tests'
on:
  pull_request:
    paths-ignore:
      - 'tests/bash/**'
      - 'tests/fixtures/**'
      - 'ani-cli'

permissions:
  contents: read

jobs:
  lint:
    name: Shellcheck + Shfmt (per-file dialect)
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify bash tests or ani-cli"'
  bats:
    name: bats-core suite
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify bash tests or ani-cli"'
