# Added due to required but conditional checks
# Read more: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: 'e2e (Playwright + Electron)'
on:
  pull_request:
    paths-ignore:
      - 'gui/backend/**'
      - 'gui/frontend/**'
      - 'gui/electron/**'
      - '.github/workflows/e2e.yml'

permissions:
  contents: read

jobs:
  e2e:
    name: Playwright + _electron
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required: did not modify backend / frontend / electron"'
